name: Compilar Tesseract

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Paso 1: Configurar GitHub Actions con la nueva versión de checkout
    - name: Checkout code
      uses: actions/checkout@v4  # Actualización a v4 para Node.js 20

    # Paso 2: Listar archivos en el directorio raíz del repositorio
    - name: Listar archivos en el directorio raíz
      run: ls -la

    # Paso 3: Descomprimir Tesseract Source
    - name: Descomprimir Tesseract
      run: unzip tesseract-main.zip -d .

    # Paso 4: Verificar que el archivo CMakeLists.txt esté presente
    - name: Verificar Tesseract Source
      run: ls -la tesseract-main

    # Paso 5: Crear el directorio para Leptonica
    - name: Crear directorio para Leptonica
      run: mkdir -p leptonica

    # Paso 6: Descomprimir Leptonica
    - name: Descomprimir Leptonica
      run: tar -xvzf leptonica-1.85.0.tar.gz -C leptonica

    # Paso 7: Extraer los datos del idioma español
    - name: Extraer Datos de Idioma Español desde ZIP
      run: unzip tesseract-ocr-3.02.spa.zip -d tesseract-main/tessdata

    # Paso 8: Instalar dependencias
    - name: Actualizar repositorios e instalar dependencias
      run: |
        sudo apt-get update -y
        sudo apt-get install -y \
        build-essential cmake pkg-config libpng-dev libjpeg-dev libtiff-dev zlib1g-dev \
        libicu-dev libpango1.0-dev libcairo2-dev

    # Paso 9: Compilar Leptonica
    - name: Compilar Leptonica
      run: |
        cd leptonica/leptonica-1.85.0
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install

    # Paso 10: Compilar Tesseract
    - name: Compilar Tesseract
      run: |
        cd tesseract-main
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install

    # Paso 11: Verificar la instalación
    - name: Verificar la instalación de Tesseract
      run: tesseract --version

    # Paso 12: Subir el binario compilado como artefacto con la nueva versión
    - name: Subir el Binario Compilado
      uses: actions/upload-artifact@v4  # Actualización a v4
      with:
        name: tesseract-bin
        path: /usr/local/bin/tesseract
