name: Compilar Tesseract

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configurar Git
      run: |
        git config --global user.email "tu-email@example.com"
        git config --global user.name "tu-nombre"

    # Descomprimir Tesseract Source
    - name: Descomprimir Tesseract
      run: unzip tesseract-main.zip -d tesseract-main

    # Verificar archivos descomprimidos
    - name: Listar Archivos Tesseract
      run: ls -la tesseract-main

    # Extraer Leptonica
    - name: Extraer Leptonica
      run: tar -xvf leptonica-1.85.0.tar.gz

    # Instalar Dependencias
    - name: Instalar Dependencias
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake pkg-config libpng-dev libjpeg-dev libtiff-dev zlib1g-dev libicu-dev

    # Compilar Leptonica
    - name: Compilar Leptonica
      run: |
        cd leptonica-1.85.0
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install

    # Extraer Datos del Idioma Espa침ol
    - name: Extraer Idioma Espa침ol
      run: unzip tesseract-ocr-3.02.spa.zip -d tesseract-main/tessdata

    # Compilar Tesseract
    - name: Compilar Tesseract
      run: |
        cd tesseract-main
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install

    # Verificar la Instalaci칩n
    - name: Verificar la Instalaci칩n
      run: tesseract --version

    # Subir el binario compilado como artefacto
    - name: Subir el Binario Compilado
      uses: actions/upload-artifact@v3
      with:
        name: tesseract-bin
        path: /usr/local/bin/tesseract
