name: Compilar Tesseract

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configurar Git
        run: git config --global --add safe.directory /github/workspace

      - name: Verificar Archivos Subidos
        run: |
          ls -la
          if [ ! -f "tesseract-main.zip" ]; then echo "Error: tesseract-main.zip no encontrado"; exit 1; fi
          if [ ! -f "tesseract-ocr-3.02.spa.zip" ]; then echo "Error: tesseract-ocr-3.02.spa.zip no encontrado"; exit 1; fi

      - name: Descomprimir Tesseract Source
        run: unzip -o tesseract-main.zip -d tesseract-main

      - name: Listar Archivos Descomprimidos
        run: ls -la tesseract-main

      - name: Extraer Datos de Idioma Español desde ZIP
        run: unzip -o tesseract-ocr-3.02.spa.zip -d tesseract-main/tessdata

      - name: Instalar Dependencias
        run: |
          sudo apt update
          sudo apt install -y g++ make autoconf libtool pkg-config \
            libpng-dev libjpeg-dev libtiff-dev zlib1g-dev libicu-dev cmake

      - name: Compilar Tesseract
        run: |
          cd tesseract-main
          if [ -d "tesseract-main" ]; then cd tesseract-main; fi
          mkdir -p build
          cd build
          cmake ..
          make -j$(nproc)

      - name: Verificar la Instalación
        run: tesseract-main/build/bin/tesseract --version

      - name: Subir el Binario Compilado
        uses: actions/upload-artifact@v3
        with:
          name: tesseract-bin
          path: tesseract-main/build/bin/tesseract
